Repository SIU-Toba/framework, pull requests merged in 2022-07, with the labels that each got.

#120 Reemplazo SecurityMultiTool
  composer.json
  php/nucleo/lib/toba_manejador_sesiones.php
  php/nucleo/lib/toba_memoria.php
Labels: enhancement, dependencies

#136 Feature/update dot env24
  bin/launcher.php
  composer.json
  composer.lock
Labels: dependencies

#137 Bugfix en validación de estado en ef_editable_fecha_hora
  php/nucleo/componentes/interface/efs/toba_ef_editable.php
Labels: bug
